import assert from 'node:assert/strict';
const base = process.env.TEST_API_URL || 'http://127.0.0.1:3001/api';
const suffix = Date.now();
async function call(path, method = 'GET', body, cookie = '', status = 200) {
 const response = await fetch(base + path, { method, headers: { ...(body ? { 'Content-Type': 'application/json' } : {}), Cookie: cookie }, body: body ? JSON.stringify(body) : undefined });
 const raw = await response.text();
 assert.equal(response.status, status, `${method} ${path}: ${raw}`);
 return { body: raw ? JSON.parse(raw) : null, cookie: response.headers.get('set-cookie')?.split(';')[0] || '' };
}
const owner = await call('/auth/register', 'POST', { name: 'Test eigenaar', email: `owner${suffix}@example.test`, password: 'test-password-12345' }, '', 201);
const reader = await call('/auth/register', 'POST', { name: 'Test lezer', email: `reader${suffix}@example.test`, password: 'test-password-12345' }, '', 201);
const outsider = await call('/auth/register', 'POST', { name: 'Test ander', email: `other${suffix}@example.test`, password: 'test-password-12345' }, '', 201);
await call('/calendars', 'GET', undefined, '', 401);
const calendars = await call('/calendars', 'GET', undefined, owner.cookie);
const calendar = calendars.body[0]; const path = `/calendars/${calendar.id}`;
await call(path + '/people', 'GET', undefined, outsider.cookie, 404);
await call(path + '/members', 'POST', { email: reader.body.email, role: 'VIEW' }, owner.cookie);
await call(path + '/people', 'POST', { name: 'Denied', initials: 'NO', color: '#123456' }, reader.cookie, 403);
const person = (await call(path + '/people', 'POST', { name: 'Lina', initials: 'LI', color: '#987654' }, owner.cookie, 201)).body;
await call(path + '/people', 'POST', { name: ' ', initials: 'LI', color: '#987654' }, owner.cookie, 400);
const input = { title: 'Tandarts', start: '2026-10-19T08:00:00Z', end: '2026-10-19T09:00:00Z', people: [person.id], recurrenceRule: 'FREQ=WEEKLY;COUNT=3', location: 'Utrecht', notes: 'Neem de kaart mee', reminderMinutes: 15 };
const event = (await call(path + '/events', 'POST', input, owner.cookie, 201)).body;
const range = '?start=2026-10-01T00:00:00Z&end=2026-11-10T00:00:00Z';
const events = (await call(path + '/events' + range, 'GET', undefined, reader.cookie)).body;
assert.equal(events.length, 3); assert.equal(events[1].start, '2026-10-26T09:00:00.000Z', 'DST keeps 10:00 Amsterdam');
await call(path + '/events', 'POST', { ...input, people: ['other-calendar-person'] }, owner.cookie, 400);
await call(path + '/events', 'POST', { ...input, recurrenceRule: 'FREQ=MINUTELY' }, owner.cookie, 400);
await call(path + '/events?start=2026-11-01T00:00:00Z&end=2026-10-01T00:00:00Z', 'GET', undefined, owner.cookie, 400);
const file = (await call(`${path}/events/${event.id}/files`, 'POST', { name: 'brief.txt', data: Buffer.from('test attachment').toString('base64') }, owner.cookie, 201)).body;
const download = await fetch(base + `${path}/events/${event.id}/files/${file.id}`, { headers: { Cookie: reader.cookie } }); assert.equal(await download.text(), 'test attachment');
await call(`${path}/events/${event.id}/files/${file.id}`, 'GET', undefined, outsider.cookie, 404);
await call(`${path}/events/${event.id}?occurrence=2026-10-26T09:00:00.000Z`, 'DELETE', undefined, owner.cookie, 204);
assert.equal((await call(path + '/events' + range, 'GET', undefined, owner.cookie)).body.length, 2);
const detached = (await call(`${path}/events/${event.id}/occurrences`, 'POST', { ...input, occurrence: input.start, title: 'Verplaatst', start: '2026-10-20T08:00:00Z', end: '2026-10-20T09:00:00Z' }, owner.cookie, 201)).body;
assert.equal(detached.recurrenceRule, null);
assert.equal((await call(`${path}/events/${detached.id}`, 'GET', undefined, owner.cookie)).body.attachments.length, 1);
const ics = 'BEGIN:VCALENDAR\r\nVERSION:2.0\r\nBEGIN:VEVENT\r\nUID:test-import\r\nDTSTART:20261021T120000Z\r\nDTEND:20261021T130000Z\r\nSUMMARY:Externe afspraak\r\nEND:VEVENT\r\nEND:VCALENDAR';
await call(path + '/import', 'POST', { content: ics }, owner.cookie);
await call(path + '/import', 'POST', { content: ics.replace('Externe afspraak', 'Bijgewerkt') }, owner.cookie);
const imported = (await call(path + '/events' + range, 'GET', undefined, owner.cookie)).body.filter(e => e.externalUid === 'test-import'); assert.equal(imported.length, 1); assert.equal(imported[0].title, 'Bijgewerkt');
const exported = await fetch(base + path + '/export', { headers: { Cookie: owner.cookie } }); assert.match(await exported.text(), /BEGIN:VCALENDAR/);
await call(path + '/members/' + reader.body.id, 'DELETE', undefined, owner.cookie, 204);
await call(path + '/people', 'GET', undefined, reader.cookie, 404);
await call('/auth/logout', 'POST', {}, owner.cookie, 204);
await call('/auth/me', 'GET', undefined, owner.cookie, 401);
console.log('PASS: accounts, sessions, calendar isolation, roles, validation, DST, recurrence exceptions, files, ICS import/export, revocation and logout.');
